export class AppConst {
  public static PAGE_SIZE_OPTIONS = [10, 20, 50];
  public static EX_MSG = 'Something went wrong';

  public static VERIFICATION_STATUS = {
    VERIFIED: 'VERIFIED',
    UNVERIFIED: 'UNVERIFIED'
  }

  public static REQUEST_TYPE = {
    BALANCE_REQUEST: "BALANCE_REQUEST",
    MERCHANT_REQUEST: "MERCHANT_REQUEST",
    TRANSFER_REQUEST: "TRANSFER_REQUEST",
    EXCHANGE_REQUEST: "EXCHANGE_REQUEST",
    WITHDRAW_REQUEST: "WITHDRAW_REQUEST",
    AD_ORDER_REQUEST: "AD_ORDER_REQUEST"
  };

  public static REQUEST_STATUS = {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED'
  }

  public static ROLES = {
    USER: 'ROLE_USER',
    ADMIN: "ROLE_ADMIN",
    MERCHANT: "ROLE_MERCHANT",
  }

  public static OTP_TYPE = {
    REGISTER: 'REGISTER',
    RESET_PASSWORD: 'RESET_PASSWORD'
  }

  public static ENTITY_DOC_TYPE = {
    TRANSACTION_PROOF: 'TRANSACTION_PROOF',
    PAYMENT_RECEIPT: 'PAYMENT_RECEIPT',
    INVOICE: 'INVOICE',
    BANK_STATEMENT: 'BANK_STATEMENT',
    SCREENSHOT: 'SCREENSHOT',
    USER_KYC_DOCUMENTS: 'USER_KYC_DOCUMENTS',
    PROFILE_IMAGE: 'PROFILE_IMAGE',
    MERCHANT_KYC_DOCUMENTS: "MERCHANT_KYC_DOCUMENTS"
  }

  public static ENTITY_MODULE_CODE = {
    BALANCE: 'BALANCE',
    MERCHANT: 'MERCHANT',
    HOME: 'HOME',
    AUTH: 'AUTH',
    AD_ORDER: 'AD_ORDER',
    USER: 'USER',
    AD_ORDER_APPEAL: 'AD_ORDER_APPEAL',
    WITHDRAW: 'WITHDRAW'
  }

  public static CURRENCY_CODE = {
    INR: 'INR',
    BDT: 'BDT',
    EUR: 'EUR',
    GBP: 'GBP',
    USDT: 'USDT'
  }

}
